FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out RealDiceEdgeModule.csproj

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

# XXX GPIOを切り離したら moduleuser でよい
# RUN useradd -ms /bin/bash moduleuser
# USER moduleuser

ENTRYPOINT ["dotnet", "RealDiceEdgeModule.dll"]