FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out RealDiceCameraModule.csproj

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

# XXX Bind port 80
# RUN useradd -ms /bin/bash moduleuser
# USER moduleuser

EXPOSE 80
ENTRYPOINT ["dotnet", "RealDiceCameraModule.dll"]