on:
  pull_request:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: RealDiceBot
  AZURE_WEBAPP_PACKAGE_PATH: './RealDiceBot'
  AZURE_FUNCTIONAPP_NAME: RealDiceBotFunctions
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './RealDiceFunctions'
  DOTNET_VERSION: '3.1.402'
  # XXX なんかセットアップに失敗するので 3.1 指定でなくフルに指定してみる
  # https://github.com/7474/RealDiceBot/runs/1149140756?check_suite_focus=true#step:3:10

jobs:
  arm:
    name: Validate ARM Template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Validate ARM Template
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az deployment group validate
          --no-prompt
          --mode Complete
          --resource-group "dicebot"
          --template-file "./DeploymentTemplates/template-with-preexisting-rg.json"
          --parameters
          baseUrl="https://realdicebot.azurewebsites.net/"
          appId="a35637a9-0577-42ee-893e-95f26f885e8d"
          appSecret="${{ secrets.REAL_DICE_BOT_SECRET }}"
          botId="${{ env.AZURE_WEBAPP_NAME }}"
          newWebAppName="${{ env.AZURE_WEBAPP_NAME }}"
          newAppServicePlanName="${{ env.AZURE_WEBAPP_NAME }}Plan"
          appServicePlanLocation="Japan East"
          functionAppName="${{ env.AZURE_FUNCTIONAPP_NAME }}"
          directLineExtensionKey="${{ secrets.DIRECT_LINE_EXTENSION_KEY }}"
          directLineSecret="${{ secrets.directLineSecret }}"
          twitterConsumerKey="${{ secrets.twitterConsumerKey }}"
          twitterConsumerSecret="${{ secrets.twitterConsumerSecret }}"
          twitterAccessToken="${{ secrets.twitterAccessToken }}"
          twitterAccessTokenSecret="${{ secrets.twitterAccessTokenSecret }}"
          ioTHubEventHubsName="${{ secrets.ioTHubEventHubsName }}"
          ioTHubEventHubsConnectionString="${{ secrets.ioTHubEventHubsConnectionString }}"
          ioTHubConnectionString="${{ secrets.ioTHubConnectionString }}"
          ioTHubRealDiceEdgeDeviceId="${{ secrets.ioTHubRealDiceEdgeDeviceId }}"
          resultContainerBaseUri="https://realdicebot66vfhffepftuc.blob.core.windows.net/realdiceresults/"
          --name "${{ env.AZURE_WEBAPP_NAME }}"

  dotnet:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # XXX 普通に考えたらここはテスト
    - name: Build solution
      shell: pwsh
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/7474/index.json -n github -u 7474 -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
        dotnet restore
        dotnet build --configuration Release
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        dotnet publish -c Release -o './myapp'
        popd
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
