on:
  release:
    types: [created]

env:
  AZURE_WEBAPP_NAME: RealDiceBot
  AZURE_WEBAPP_PACKAGE_PATH: './RealDiceBot'
  AZURE_FUNCTIONAPP_NAME: RealDiceBotFunctions
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './RealDiceFunctions'
  DOTNET_VERSION: '3.1'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build solution and publish projects
      shell: pwsh
      run: |
        dotnet restore
        dotnet build --configuration Release
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        dotnet publish -c Release -o './myapp'
        popd
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # --no-wait オプションを付ければジョブはすぐ完了するが、それではデプロイ結果が分からないので待つ。
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az deployment group create
          --no-prompt
          --mode Complete
          --resource-group "dicebot"
          --template-file "./DeploymentTemplates/template-with-preexisting-rg.json"
          --parameters
          appId="a35637a9-0577-42ee-893e-95f26f885e8d"
          appSecret="${{ secrets.REAL_DICE_BOT_SECRET }}"
          botId="${{ env.AZURE_WEBAPP_NAME }}"
          newWebAppName="${{ env.AZURE_WEBAPP_NAME }}"
          newAppServicePlanName="${{ env.AZURE_WEBAPP_NAME }}Plan"
          appServicePlanLocation="Japan East"
          functionAppName="${{ env.AZURE_FUNCTIONAPP_NAME }}"
          --name "${{ env.AZURE_WEBAPP_NAME }}"

    - name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
